### ISSUE TITLE
ASAN: SEGV slang-nightly/source/numeric/SVInt.cpp:1365:13 in slang::SVInt::operator<(slang::SVInt const&) const

### ISSUE THREAD

**Issue by chengniansun** [MikePopoloski/slang#469]
## Compiler Version

```
slang version 0.9.
```

## System Information

```
Linux 5.4.0-80-generic x86_64 GNU/Linux
```

## Minimized Code

```
if mlog2 (32'd1;
function mlog2
input [1024 : 0 value
for ;
value > 32'd0
value = value >> 1
```

## Output

```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==1201337==ERROR: AddressSanitizer: SEGV on unknown address 0x60d020000d38 (pc 0x00000212598c bp 0x7ffe6c1c7a70 sp 0x7ffe6c1c7660 T0)
==1201337==The signal is caused by a READ memory access.
    #0 0x212598c in slang::SVInt::operator<(slang::SVInt const&) const /tmp/tmp.KA8AI6Dl6t/slang-nightly/source/numeric/SVInt.cpp:1365:13
    #1 0x13bd0be in slang::SVInt::operator<=(slang::SVInt const&) const /tmp/tmp.KA8AI6Dl6t/slang-nightly/source/../include/slang/numeric/SVInt.h:465:64
    #2 0x13bcda5 in slang::SVInt::operator>(slang::SVInt const&) const /tmp/tmp.KA8AI6Dl6t/slang-nightly/source/../include/slang/numeric/SVInt.h:466:64
    #3 0x1377988 in slang::Expression::evalBinaryOperator(slang::BinaryOperator, slang::ConstantValue const&, slang::ConstantValue const&) /tmp/tmp.KA8AI6Dl6t/slang-nightly/source/binding/OperatorExpressions.cpp:2120:17
    #4 0x1374716 in slang::BinaryExpression::evalImpl(slang::EvalContext&) const /tmp/tmp.KA8AI6Dl6t/slang-nightly/source/binding/OperatorExpressions.cpp:910:12
    #5 0x120e1a5 in slang::ConstantValue (anonymous namespace)::EvalVisitor::visit<slang::BinaryExpression>(slang::BinaryExpression const&, slang::EvalContext&) /tmp/tmp.KA8AI6Dl6t/slang-nightly/source/binding/Expression.cpp:35:33
    #6 0x12031cf in decltype(auto) slang::Expression::visitExpression<slang::Expression const, (anonymous namespace)::EvalVisitor&, slang::EvalContext&>(slang::Expression const*, (anonymous namespace)::EvalVisitor&, slang::EvalContext&) const /tmp/tmp.KA8AI6Dl6t/slang-nightly/source/../include/slang/symbols/ASTVisitor.h:290:9
    #7 0x11f5dd6 in decltype(auto) slang::Expression::visit<(anonymous namespace)::EvalVisitor&, slang::EvalContext&>((anonymous namespace)::EvalVisitor&, slang::EvalContext&) const /tmp/tmp.KA8AI6Dl6t/slang-nightly/source/../include/slang/symbols/ASTVisitor.h:326:12
    #8 0x11f5c45 in slang::Expression::eval(slang::EvalContext&) const /tmp/tmp.KA8AI6Dl6t/slang-nightly/source/binding/Expression.cpp:334:12
    #9 0x149502f in slang::ForLoopStatement::evalImpl(slang::EvalContext&) const /tmp/tmp.KA8AI6Dl6t/slang-nightly/source/binding/Statements.cpp:1281:37
    #10 0x14ad991 in slang::Statement::EvalResult (anonymous namespace)::EvalVisitor::visit<slang::ForLoopStatement>(slang::ForLoopStatement const&, slang::EvalContext&) /tmp/tmp.KA8AI6Dl6t/slang-nightly/source/binding/Statements.cpp:36:21
    #11 0x145479b in decltype(auto) slang::Statement::visit<(anonymous namespace)::EvalVisitor&, slang::EvalContext&>((anonymous namespace)::EvalVisitor&, slang::EvalContext&) const /tmp/tmp.KA8AI6Dl6t/slang-nightly/source/../include/slang/symbols/ASTVisitor.h:228:9
    #12 0x1453343 in slang::Statement::eval(slang::EvalContext&) const /tmp/tmp.KA8AI6Dl6t/slang-nightly/source/binding/Statements.cpp:67:12
    #13 0x10e0f81 in slang::CallExpression::evalImpl(slang::EvalContext&) const /tmp/tmp.KA8AI6Dl6t/slang-nightly/source/binding/CallExpression.cpp:639:38
    #14 0x1216125 in slang::ConstantValue (anonymous namespace)::EvalVisitor::visit<slang::CallExpression>(slang::CallExpression const&, slang::EvalContext&) /tmp/tmp.KA8AI6Dl6t/slang-nightly/source/binding/Expression.cpp:35:33
    #15 0x1203f71 in decltype(auto) slang::Expression::visitExpression<slang::Expression const, (anonymous namespace)::EvalVisitor&, slang::EvalContext&>(slang::Expression const*, (anonymous namespace)::EvalVisitor&, slang::EvalContext&) const /tmp/tmp.KA8AI6Dl6t/slang-nightly/source/../include/slang/symbols/ASTVisitor.h:300:9
    #16 0x11f5dd6 in decltype(auto) slang::Expression::visit<(anonymous namespace)::EvalVisitor&, slang::EvalContext&>((anonymous namespace)::EvalVisitor&, slang::EvalContext&) const /tmp/tmp.KA8AI6Dl6t/slang-nightly/source/../include/slang/symbols/ASTVisitor.h:326:12
    #17 0x11f5c45 in slang::Expression::eval(slang::EvalContext&) const /tmp/tmp.KA8AI6Dl6t/slang-nightly/source/binding/Expression.cpp:334:12
    #18 0x11c5a26 in slang::BindContext::eval(slang::Expression const&) const /tmp/tmp.KA8AI6Dl6t/slang-nightly/source/binding/BindContext.cpp:181:33
    #19 0xbdddf7 in slang::GenerateBlockSymbol::fromSyntax(slang::Compilation&, slang::IfGenerateSyntax const&, slang::LookupLocation, slang::Scope const&, unsigned int, bool, slang::SmallVector<slang::GenerateBlockSymbol*>&) /tmp/tmp.KA8AI6Dl6t/slang-nightly/source/symbols/BlockSymbols.cpp:295:40
    #20 0xdea2f7 in slang::Scope::elaborate() const /tmp/tmp.KA8AI6Dl6t/slang-nightly/source/symbols/Scope.cpp:766:17
    #21 0x7fbdff in slang::Scope::ensureElaborated() const /tmp/tmp.KA8AI6Dl6t/slang-nightly/source/../include/slang/symbols/Scope.h:225:13
    #22 0x7fcf62 in slang::Scope::members() const /tmp/tmp.KA8AI6Dl6t/slang-nightly/source/../include/slang/symbols/Scope.h:190:9
    #23 0x9047aa in void slang::ASTVisitor<slang::DiagnosticVisitor, false, false>::visitDefault<slang::CompilationUnitSymbol>(slang::CompilationUnitSymbol const&) /tmp/tmp.KA8AI6Dl6t/slang-nightly/source/../include/slang/symbols/ASTVisitor.h:88:35
    #24 0x904547 in bool slang::DiagnosticVisitor::handleDefault<slang::CompilationUnitSymbol>(slang::CompilationUnitSymbol const&) /tmp/tmp.KA8AI6Dl6t/slang-nightly/source/compilation/ElabVisitors.h:57:9
    #25 0x903cc2 in void slang::DiagnosticVisitor::handle<slang::CompilationUnitSymbol>(slang::CompilationUnitSymbol const&) /tmp/tmp.KA8AI6Dl6t/slang-nightly/source/compilation/ElabVisitors.h:24:9
    #26 0x8fdc78 in void slang::ASTVisitor<slang::DiagnosticVisitor, false, false>::visit<slang::CompilationUnitSymbol>(slang::CompilationUnitSymbol const&) /tmp/tmp.KA8AI6Dl6t/slang-nightly/source/../include/slang/symbols/ASTVisitor.h:63:43
    #27 0x8ad9f3 in decltype(auto) slang::Symbol::visit<slang::DiagnosticVisitor&>(slang::DiagnosticVisitor&) const /tmp/tmp.KA8AI6Dl6t/slang-nightly/source/../include/slang/symbols/ASTVisitor.h:129:9
    #28 0x903bab in void slang::ASTVisitor<slang::DiagnosticVisitor, false, false>::visitDefault<slang::RootSymbol>(slang::RootSymbol const&) /tmp/tmp.KA8AI6Dl6t/slang-nightly/source/../include/slang/symbols/ASTVisitor.h:89:24
    #29 0x903747 in bool slang::DiagnosticVisitor::handleDefault<slang::RootSymbol>(slang::RootSymbol const&) /tmp/tmp.KA8AI6Dl6t/slang-nightly/source/compilation/ElabVisitors.h:57:9
    #30 0x902ec2 in void slang::DiagnosticVisitor::handle<slang::RootSymbol>(slang::RootSymbol const&) /tmp/tmp.KA8AI6Dl6t/slang-nightly/source/compilation/ElabVisitors.h:24:9
    #31 0x8fdba8 in void slang::ASTVisitor<slang::DiagnosticVisitor, false, false>::visit<slang::RootSymbol>(slang::RootSymbol const&) /tmp/tmp.KA8AI6Dl6t/slang-nightly/source/../include/slang/symbols/ASTVisitor.h:63:43
    #32 0x8ad8e3 in decltype(auto) slang::Symbol::visit<slang::DiagnosticVisitor&>(slang::DiagnosticVisitor&) const /tmp/tmp.KA8AI6Dl6t/slang-nightly/source/../include/slang/symbols/ASTVisitor.h:128:9
    #33 0x847649 in slang::Compilation::getSemanticDiagnostics() /tmp/tmp.KA8AI6Dl6t/slang-nightly/source/compilation/Compilation.cpp:836:15
    #34 0x869605 in slang::Compilation::getAllDiagnostics() /tmp/tmp.KA8AI6Dl6t/slang-nightly/source/compilation/Compilation.cpp:949:39
    #35 0x74e848 in Compiler::run() /tmp/tmp.KA8AI6Dl6t/slang-nightly/tools/driver/driver.cpp:305:43
    #36 0x62148e in int driverMain<char**>(int, char**, bool, bool) /tmp/tmp.KA8AI6Dl6t/slang-nightly/tools/driver/driver.cpp:714:36
    #37 0x6087af in main /tmp/tmp.KA8AI6Dl6t/slang-nightly/tools/driver/driver.cpp:809:12
    #38 0x7fbb8f8790b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16
    #39 0x55384d in _start (/scratch/software/slang-trunk/bin/slang+0x55384d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /tmp/tmp.KA8AI6Dl6t/slang-nightly/source/numeric/SVInt.cpp:1365:13 in slang::SVInt::operator<(slang::SVInt const&) const
==1201337==ABORTING
```

**Comment by MikePopoloski** [comment]
Fixed in 514ed0a85f8a864f2ebe9cec4ecaf3acdd963b69
