### ISSUE TITLE
segfault on parsing extern task argument with default value

### ISSUE THREAD

**Issue by jrudess** [MikePopoloski/slang#475]
From trying to minimize the original code, I found I could only reproduce the segfault when the task is extern and the default value is specified.

```systemverilog
class C;
    extern task f(bit[7:0] i[$]='{});
endclass

task C::f(bit[7:0] i[$]='{});
endtask
```

Backtrace
```
#0  slang::Token::rawText (this=0x7fffffffc170) at slang/source/parsing/Token.cpp:253
#1  0x00005555558dd559 in slang::Token::valueText (this=0x7fffffffc170) at slang/source/parsing/Token.cpp:228
#2  0x00005555556d1603 in slang::isSameExpr (l=..., r=...) at slang/source/symbols/SubroutineSymbols.cpp:269
#3  0x00005555556d1bf2 in slang::SubroutineSymbol::createOutOfBlock (compilation=..., syntax=..., prototype=..., parent=..., definitionScope=..., 
    outOfBlockIndex=(unknown: 0x2)) at slang/source/symbols/SubroutineSymbols.cpp:345
#4  0x00005555556d4dbe in slang::MethodPrototypeSymbol::getSubroutine (this=0x555555cedc78) at slang/source/symbols/SubroutineSymbols.cpp:866
#5  0x00005555555dd136 in slang::DiagnosticVisitor::handle (this=0x7fffffffcdb0, symbol=...) at slang/source/compilation/ElabVisitors.h:90
#6  0x00005555555e57f1 in slang::ASTVisitor<slang::DiagnosticVisitor, false, false>::visit<slang::MethodPrototypeSymbol> (this=0x7fffffffcdb0, t=...)
    at slang/source/../include/slang/symbols/ASTVisitor.h:63
#7  0x00005555555ddefe in slang::Symbol::visit<slang::DiagnosticVisitor&> (this=0x555555cedc78, visitor=...)
    at slang/source/../include/slang/symbols/ASTVisitor.h:162
#8  0x00005555556187a4 in slang::ASTVisitor<slang::DiagnosticVisitor, false, false>::visitDefault<slang::ClassType> (this=0x7fffffffcdb0, t=...)
    at slang/source/../include/slang/symbols/ASTVisitor.h:89
#9  0x0000555555606495 in slang::DiagnosticVisitor::handleDefault<slang::ClassType> (this=0x7fffffffcdb0, symbol=...)
    at slang/source/compilation/ElabVisitors.h:57
#10 0x00005555555f2821 in slang::DiagnosticVisitor::handle<slang::ClassType> (this=0x7fffffffcdb0, symbol=...)
    at slang/source/compilation/ElabVisitors.h:24
#11 0x00005555555e5c8b in slang::ASTVisitor<slang::DiagnosticVisitor, false, false>::visit<slang::ClassType> (this=0x7fffffffcdb0, t=...)
    at slang/source/../include/slang/symbols/ASTVisitor.h:63
#12 0x00005555555de2a0 in slang::Symbol::visit<slang::DiagnosticVisitor&> (this=0x555555cedbb0, visitor=...)
    at slang/source/../include/slang/symbols/ASTVisitor.h:193
#13 0x0000555555617bc0 in slang::ASTVisitor<slang::DiagnosticVisitor, false, false>::visitDefault<slang::CompilationUnitSymbol> (this=0x7fffffffcdb0, t=...)
    at source/../include/slang/symbols/ASTVisitor.h:89
#14 0x000055555560318d in slang::DiagnosticVisitor::handleDefault<slang::CompilationUnitSymbol> (this=0x7fffffffcdb0, symbol=...)
    at slang/source/compilation/ElabVisitors.h:57
#15 0x00005555555f2199 in slang::DiagnosticVisitor::handle<slang::CompilationUnitSymbol> (this=0x7fffffffcdb0, symbol=...)
    at slang/source/compilation/ElabVisitors.h:24
#16 0x00005555555e5331 in slang::ASTVisitor<slang::DiagnosticVisitor, false, false>::visit<slang::CompilationUnitSymbol> (this=0x7fffffffcdb0, t=...)
    at source/../include/slang/symbols/ASTVisitor.h:63
#17 0x00005555555ddb20 in slang::Symbol::visit<slang::DiagnosticVisitor&> (this=0x555555ceda40, visitor=...)
    at source/../include/slang/symbols/ASTVisitor.h:129
#18 0x0000555555617afc in slang::ASTVisitor<slang::DiagnosticVisitor, false, false>::visitDefault<slang::RootSymbol> (this=0x7fffffffcdb0, t=...)
    at source/../include/slang/symbols/ASTVisitor.h:89
#19 0x0000555555603071 in slang::DiagnosticVisitor::handleDefault<slang::RootSymbol> (this=0x7fffffffcdb0, symbol=...)
    at source/compilation/ElabVisitors.h:57
#20 0x00005555555f2173 in slang::DiagnosticVisitor::handle<slang::RootSymbol> (this=0x7fffffffcdb0, symbol=...)
    at slang/source/compilation/ElabVisitors.h:24
#21 0x00005555555e530b in slang::ASTVisitor<slang::DiagnosticVisitor, false, false>::visit<slang::RootSymbol> (this=0x7fffffffcdb0, t=...)
    at slang/source/../include/slang/symbols/ASTVisitor.h:63
#22 0x00005555555ddb02 in slang::Symbol::visit<slang::DiagnosticVisitor&> (this=0x555555cd5a60, visitor=...)
    at slang/source/../include/slang/symbols/ASTVisitor.h:128
#23 0x00005555555d53a8 in slang::Compilation::getSemanticDiagnostics (this=0x7fffffffd8c0) at source/compilation/Compilation.cpp:851
#24 0x00005555555d6029 in slang::Compilation::getAllDiagnostics (this=0x7fffffffd8c0) at source/compilation/Compilation.cpp:964
#25 0x000055555558a8aa in Compiler::run (this=0x7fffffffd4b0) at tools/driver/driver.cpp:305
#26 0x00005555555917a6 in driverMain<char**> (argc=2, argv=0x7fffffffe3e8, suppressColorsStdout=false, suppressColorsStderr=false)
    at tools/driver/driver.cpp:714
#27 0x0000555555587a70 in main (argc=2, argv=0x7fffffffe3e8) at tools/driver/driver.cpp:809
```

**Comment by MikePopoloski** [comment]
Fixed in 63cae8b96066cc0ce4dc0e6a32d1f2967b08dee5
